### PR TITLE
Use HTTPs based submodule paths

### PR DESCRIPTION
**Pull request by Al12rs**
git@ based reference require user authentication during clone, which isn't useful for an open source project.

fixes https://github.com/Nexus-Mods/NexusMods.App/issues/590

### CODE REVIEW

**Review by Sewer56 — APPROVED** [review]
I did this change in another repo before so LGTM

**Comment by Al12rs** [comment]
The tests seem to be stuck on waiting, I can't seem to merge.

**Comment by Sewer56** [comment]
Well, this is weird...

**Comment by Al12rs** [comment]
@halgari any clues what might be happening here? I see the same thing on the bot submodule update PR

**Comment by erri120** [comment]
The tests are marked as "expected", however, they don't run because none of the source files have been updated.

**Pull request merged**
